# action.yml
name: 'Code Quality Score'
description: 'Calculate the code quality score for the code based on reek, flay, and flog'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  total_score: # id of output
    description: 'The total score'
  similarity_score_per_file: 
    'Average similarity score by code files (based on flay)',
  abc_method_average: 
    'Average abc method score (based on flog)',
  code_smells_per_file: 
    'Average number of code smells per file (based on reek)'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}