# action.yml
name: 'Code Quality Score'
description: 'Calculate the code quality score for the code based on reek, flay, and flog'
inputs:
  code_folder:  # id of input
    description: Code folder (either app or lib)
    required: true
    default: 'app'
outputs:
  total_score: # id of output
    description: 'The total score'
  similarity_score_per_file: 
    description: 'Average similarity score by code files (based on flay)',
  abc_method_average: 
    description: 'Average abc method score (based on flog)',
  code_smells_per_file: 
    description: 'Average number of code smells per file (based on reek)'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.code_folder }}