#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/code_quality_score"

# inputs
relative_path = ARGV[0] || "./"
puts "Calculating score snapshot for #{relative_path}..."

# calculate score snapshot
score_snapshot = CodeQualityScore::ScoreSnapshot.new(repository_path: relative_path).calculate_score
puts(score_snapshot)
