#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/code_quality_score"

# inputs
base_relative_path = ARGV[0] || "./"
pr_relative_path = ARGV[1] || "./"

# calculate
base_score_snapshot = CodeQualityScore::ScoreSnapshot.new(repository_path: base_relative_path).calculate_score
pr_score_snapshot = CodeQualityScore::ScoreSnapshot.new(repository_path: pr_relative_path).calculate_score

# format
CodeQualityScore::FormatComparison.format_as_markdown(base_score_snapshot, pr_score_snapshot)
