#!/usr/bin/env ruby
# frozen_string_literal: true

require "code_quality_score/score_snapshotter"

# inputs
is_gem = ARGV[0] == "lib"
relative_path = ARGV[1] || "./"
puts "Calculating score snapshot for #{is_gem ? "gem" : "app"} in folder #{relative_path}..."

# calculate score snapshot
score_snapshot = CodeQualityScore::ScoreSnapshotter.calculate_score_snapshot(is_gem, relative_path_to_repository: relative_path)
puts(score_snapshot)
